### ISSUE TITLE
Support for Null-safety!

### ISSUE THREAD

**Issue by xscotophilic** [abuanwar072/Recipe-App---Flutter-UI#1]
### Some of the code doesn't work when we use Null-Safety.

For example (size_config.dart):
```
import 'package:flutter/widgets.dart';

class SizeConfig {
  static MediaQueryData _mediaQueryData;
  static double screenWidth;
  static double screenHeight;
  static double defaultSize;
  static Orientation orientation;

  void init(BuildContext context) {
    _mediaQueryData = MediaQuery.of(context);
    screenWidth = _mediaQueryData.size.width;
    screenHeight = _mediaQueryData.size.height;
    orientation = _mediaQueryData.orientation;
    // On iPhone 11 the defaultSize = 10 almost
    // So if the screen size increase or decrease then our defaultSize also vary
    defaultSize = orientation == Orientation.landscape
        ? screenHeight * 0.024
        : screenWidth * 0.024;
  }
}
```
![ss](https://user-images.githubusercontent.com/47301282/121784502-d362c100-cbd1-11eb-833d-1ca5917440f9.png)

**The non-nullable variable '_mediaQueryData' must be initialized. Try adding an initializer expression.**

**Comment by xscotophilic** [comment]
Using late keyword will solve the issue!
![ss](https://user-images.githubusercontent.com/47301282/121786469-8258ca00-cbdd-11eb-9dbc-da2d6b5a408c.png)

**Comment by hafisn07** [comment]
Because of null safety your variable must be initialzied when created, to fix this you can use late to tell it that it will be initialized after being created but before being used.

**Comment by xscotophilic** [comment]
Yes, I was beginner at that time, now I understand.
